Create 2024-07-03-csail-network
CCI-MOC/moc-status pull request #55
Opened 2024-07-03 19:29 UTC by msdisme

Notification of possible ESI and MAAS service interruption on July 15, 2024

2024-07-03 20:24 UTC, joachimweyl commented on _posts/2024-07-03-csail-network
> +published: false
I think if you want it published you need to remove this line or add a # before it

2024-07-03 20:27 UTC, hakasapl requested changes
File is not saved as .md file

2024-07-03 20:27 UTC, hakasapl commented on _posts/2024-07-03-csail-network
> +-->
We don't need the template lines

2024-07-03 20:35 UTC, joachimweyl commented on _posts/2024-07-03-csail-network
> +severity: 1
severity 0 until 15th

2024-07-26 13:47 UTC, joachimweyl commented
no longer needed

2024-07-26 13:47 UTC, closed without merging